### ISSUE TITLE
Create beginner-friendly markdown file around source control, git and github

### ISSUE THREAD

**Issue by CristinaRuth** [CristinaRuth/dev-together-workshop-github-basics#16]
We used the presentation below to help beginners understand what source control, Git and Github are.

https://docs.google.com/presentation/d/1o78CV_huVXuK9IWuLFwoLwQeXjwNLf_wGkF5tnlgrRY/edit?usp=sharing

But it contains other information specific to Dev Together and our sponsor at the time.

Can we create a new markdown file that takes the necessary content from above so users can use that as an easier reference?

We would then need to update the main `README` file to point to that file.

**Comment by steveperkins** [comment]
Addressed by PR#18

**Comment by CristinaRuth** [comment]
@steveperkins could we update the main Readme file to point towards the new markdown you've created? 🙂

**Comment by steveperkins** [comment]
Ha, I forgot! I'll send a PR in a minute.
